/**
 * Point d’entrée rétrocompatible — préférer les imports depuis `./config/*`.
 */
export {
  BUILDER_URL,
  BUILDER_LOGIN_URL,
  BUILDER_REGISTER_URL,
  BUILDER_BILLING_URL,
  SITE_URL,
  SITE_NAME,
  SITE_TAGLINE,
  CONTACT_EMAIL,
  CONTACT_FORM_WEBHOOK_DEFAULT,
  COOKIE_CONSENT_STORAGE_KEY,
  COOKIE_CONSENT_VERSION,
  GOOGLE_ANALYTICS_ID,
  SOCIAL_OG_IMAGE,
  VALUE_PROPOSITION,
} from './config/site';
