import type { Integration } from './types';

/**
 * Connecteurs confirmés dans builder/src/ServiceIntegration/ServiceIntegrationType.php.
 * Les marques citées appartiennent à leurs propriétaires respectifs.
 */
export const integrations: Integration[] = [
  {
    id: 'mailjet',
    name: 'Mailjet',
    category: 'email',
    status: 'available',
    description:
      'Envoyez des e-mails transactionnels à partir de modèles Mailjet, avec mapping des variables du payload.',
    actions: ['Envoi via template Mailjet', 'Variables dynamiques', 'Journalisation MessageID / MessageUUID'],
    prerequisites: ['Compte Mailjet', 'Clés API publique et privée', 'Modèle configuré côté Mailjet'],
    documentationUrl: '/integrations/mailjet/',
    detailUrl: '/integrations/mailjet/',
    vendorUrl: 'https://www.mailjet.com/',
  },
  {
    id: 'http_webhook',
    name: 'HTTP personnalisé',
    category: 'http',
    status: 'available',
    description: 'Appelez une URL ou une API tierce pour transmettre ou enrichir un événement.',
    actions: ['POST / requête HTTP sortante', 'Transfert de payload'],
    prerequisites: ['URL HTTPS de destination', 'Éventuels en-têtes d’authentification'],
    documentationUrl: '/documentation/',
    vendorUrl: undefined,
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'messaging',
    status: 'available',
    description: 'Publiez une notification dans un canal Slack via un webhook entrant.',
    actions: ['Notification canal'],
    prerequisites: ['Webhook entrant Slack'],
    documentationUrl: '/integrations/',
    vendorUrl: 'https://slack.com/',
  },
  {
    id: 'teams',
    name: 'Microsoft Teams',
    category: 'messaging',
    status: 'available',
    description: 'Envoyez une alerte vers un canal Teams via un connecteur entrant.',
    actions: ['Notification canal'],
    prerequisites: ['Connecteur entrant Teams'],
    documentationUrl: '/integrations/',
    vendorUrl: 'https://www.microsoft.com/microsoft-teams',
  },
  {
    id: 'discord',
    name: 'Discord',
    category: 'messaging',
    status: 'available',
    description: 'Notifiez un serveur Discord à partir d’un événement webhook.',
    actions: ['Message webhook Discord'],
    prerequisites: ['URL de webhook Discord'],
    documentationUrl: '/integrations/',
    vendorUrl: 'https://discord.com/',
  },
  {
    id: 'google_chat',
    name: 'Google Chat',
    category: 'messaging',
    status: 'available',
    description: 'Poussez un message dans un espace Google Chat.',
    actions: ['Notification espace'],
    prerequisites: ['Webhook Google Chat'],
    documentationUrl: '/integrations/',
    vendorUrl: 'https://workspace.google.com/products/chat/',
  },
  {
    id: 'mattermost',
    name: 'Mattermost',
    category: 'messaging',
    status: 'available',
    description: 'Intégrez Mattermost pour des notifications d’équipe auto-hébergées.',
    actions: ['Notification canal'],
    prerequisites: ['Webhook entrant Mattermost'],
    documentationUrl: '/integrations/',
    vendorUrl: 'https://mattermost.com/',
  },
  {
    id: 'telegram',
    name: 'Telegram',
    category: 'messaging',
    status: 'available',
    description: 'Envoyez un message via un bot Telegram.',
    actions: ['Message bot'],
    prerequisites: ['Bot Telegram et jeton'],
    documentationUrl: '/integrations/',
    vendorUrl: 'https://telegram.org/',
  },
  {
    id: 'twilio_sms',
    name: 'Twilio SMS',
    category: 'sms',
    status: 'available',
    description: 'Déclenchez l’envoi d’un SMS via Twilio.',
    actions: ['Envoi SMS'],
    prerequisites: ['Compte Twilio', 'Identifiants API'],
    documentationUrl: '/integrations/',
    vendorUrl: 'https://www.twilio.com/',
  },
  {
    id: 'vonage_sms',
    name: 'Vonage SMS',
    category: 'sms',
    status: 'available',
    description: 'Envoyez des SMS via l’API Vonage.',
    actions: ['Envoi SMS'],
    prerequisites: ['Compte Vonage', 'Identifiants API'],
    documentationUrl: '/integrations/',
    vendorUrl: 'https://www.vonage.com/',
  },
  {
    id: 'messagebird_sms',
    name: 'MessageBird SMS',
    category: 'sms',
    status: 'available',
    description: 'Envoyez des SMS via MessageBird.',
    actions: ['Envoi SMS'],
    prerequisites: ['Compte MessageBird', 'Clé API'],
    documentationUrl: '/integrations/',
    vendorUrl: 'https://bird.com/',
  },
  {
    id: 'smsfactor_sms',
    name: 'SMSFactor',
    category: 'sms',
    status: 'available',
    description: 'Envoyez des SMS professionnels via l’API SMSFactor (made in France).',
    actions: ['Envoi SMS'],
    prerequisites: ['Compte SMSFactor', 'Jeton API', 'Crédits SMS'],
    documentationUrl: '/integrations/',
    vendorUrl: 'https://www.smsfactor.com/',
  },
  {
    id: 'pushover',
    name: 'Pushover',
    category: 'notification',
    status: 'available',
    description: 'Recevez des notifications push sur vos appareils via Pushover.',
    actions: ['Notification push'],
    prerequisites: ['Compte Pushover', 'Jetons utilisateur / application'],
    documentationUrl: '/integrations/',
    vendorUrl: 'https://pushover.net/',
  },
  {
    id: 'pacflow',
    name: 'Pacflow',
    category: 'other',
    status: 'available',
    description: 'Connectez un flux Pacflow pour relayer des événements métier.',
    actions: ['Webhook entrant Pacflow'],
    prerequisites: ['Endpoint Pacflow configuré'],
    documentationUrl: '/integrations/',
    vendorUrl: 'https://api.pacflow.fr/',
  },
];

export const INTEGRATION_DISCLAIMER =
  'Les marques et noms de produits cités appartiennent à leurs propriétaires respectifs. Leur mention n’implique aucun partenariat exclusif.';
